jobId: uwie_v194
trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-8
  masterConfig:
    acceleratorConfig:
      count: 2
      type: NVIDIA_TESLA_P4
    imageUri: gcr.io/cloud-ml-public/training/pytorch-gpu.1-4
  args:
    - "--name"
    - "uwie_v1901603173146"
    - "--dataroot"
    - "gs://arkadip-uie-store/dataset/underwater_dark"
    - "--batch_size"
    - "4"
    - "--num_threads"
    - "4"
    - "--lambda_identity"
    - "0"
    - "--norm"
    - "batch"
#    - "--ct"
#    - "120"
#    - "--n_epochs"
#    - "100"
#    - "--n_epochs_decay"
#    - "150"