jobId: uwie_v1310
trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-8
  masterConfig:
    acceleratorConfig:
      count: 2
      type: NVIDIA_TESLA_P4
    imageUri: gcr.io/cloud-ml-public/training/pytorch-gpu.1-4
  args:
    - "--name"
    - "uwie_v1310"
    - "--dataroot"
    - "gs://arkadip-uie-store/dataset/underwater_dark"
    - "--batch_size"
    - "4"