jobId: uwie_v123
trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-16
  masterConfig:
    acceleratorConfig:
      count: 1
      type: NVIDIA_TESLA_P4
    imageUri: gcr.io/cloud-ml-public/training/pytorch-gpu.1-4
  args:
    - "--dataroot"
    - "gs://arkadip-uie-store/dataset/underwater_dark"
    - "--gpu_ids"
    - "0"